### ISSUE TITLE
Deserialization errors

### ISSUE THREAD

**Issue by gappleto97** [p2p-today/p2p-project#123]
This has been happening fairly consistently since I moved to bytearray storage. Here's the (not terribly helpful) traceback:

```python
Traceback (most recent call last):
  File "/home/gappleto97/git.p2p.today/py_src/base.py", line 785, in process_data
    handler.found_terminator()
  File "/home/gappleto97/git.p2p.today/py_src/mesh.py", line 48, in found_terminator
    msg = super(mesh_connection, self).found_terminator()
  File "/home/gappleto97/git.p2p.today/py_src/base.py", line 682, in found_terminator
    msg = InternalMessage.feed_string(raw_msg, False, self.compression)
  File "/home/gappleto97/git.p2p.today/py_src/base.py", line 458, in feed_string
    string = cls.__sanitize_string(string, sizeless)
  File "/home/gappleto97/git.p2p.today/py_src/base.py", line 372, in __sanitize_string
    unpack_value(string[:4]) + 4
AssertionError: Real message size 4 != expected size 171
```

**Comment by gappleto97** [comment]
As a note: This seems to happening either entirely, or almost entirely, on Python 3. I have yet to see this in Python 2. I'm currently running some tests now which should produce something like this, if this bug is present in Python 2.

**Comment by gappleto97** [comment]
As a note, this is definitely happening in both Python 2 and 3
