### ISSUE TITLE
RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by MatthewScholefield** [p2p-today/p2p-project#156]
When constantly reading and writing to the connection, within a few seconds I always get this:
```
Traceback (most recent call last):
  File "/home/matthew/Documents/GitHub/vokiso/.venv/lib/python3.6/site-packages/py2p/base.py", line 314, in process_data
    handler.found_terminator()
  File "/home/matthew/Documents/GitHub/vokiso/.venv/lib/python3.6/site-packages/py2p/mesh.py", line 63, in found_terminator
    elif self.handle_waterfall(msg, packets):
  File "/home/matthew/Documents/GitHub/vokiso/.venv/lib/python3.6/site-packages/py2p/mesh.py", line 103, in handle_waterfall
    elif not self.server.waterfall(Message(msg, self.server)):
  File "/home/matthew/Documents/GitHub/vokiso/.venv/lib/python3.6/site-packages/py2p/mesh.py", line 530, in waterfall
    self.__clean_waterfalls()
  File "/home/matthew/Documents/GitHub/vokiso/.venv/lib/python3.6/site-packages/py2p/mesh.py", line 512, in __clean_waterfalls
    self.waterfalls = {i for i in self.waterfalls if i[1] > getUTC() - 60}
  File "/home/matthew/Documents/GitHub/vokiso/.venv/lib/python3.6/site-packages/py2p/mesh.py", line 512, in <setcomp>
    self.waterfalls = {i for i in self.waterfalls if i[1] > getUTC() - 60}
RuntimeError: Set changed size during iteration
```
I'm assuming it's a race condition of some sort.

Edit: This is actually an issue with `py2p`. Just realized I posted it here.

**Comment by LivInTheLookingGlass** [comment]
Hmmm. Looks like you are probably right. I dont think that I can investigate in depth until the weekend, but I will see if I can make a quick patch for that. Probably it is as simple as making a lock for waterfalls.

Might as well add a performance improvement as well. No need to check the time for every single loop through the set.

**Comment by MatthewScholefield** [comment]
Yeah, I added a lock and it fixed it.

**Comment by LivInTheLookingGlass** [comment]
If you don't mind, could you submit a PR of that?

**Comment by LivInTheLookingGlass** [comment]
Hi, I was wondering if you could submit a pull request for that lock, since you have already done it.

**Comment by MatthewScholefield** [comment]
Yeah, I'll submit a PR. Just haven't had time recently. Should get time later today.
